version: "3"

services:
  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - TZ=Asia/Seoul
      - MARIADB_RANDOM_ROOT_PASSWORD=true
      - MARIADB_DATABASE=web_board
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=pass
